import Sidebar from "@/components/sidebar";
import "../assets/styles/globals.css";

import RootProvider from "@/providers/root-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
	src: "../assets/fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../assets/fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "PDF Document Generator",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<RootProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased dark flex flex-col w-full min-h-screen`}
				>
					<Sidebar />
					<section className="flex-1 pl-[280px]">
						{children}
					</section>
				</body>
			</RootProvider>
		</html>
	);
}
